student/urls.py
from django.urls import path
from student import views

app_name = 'student'

urlpatterns = [
    path('', views.index, name='index'),
    path('student/register/', views.registerView, name='register'),
    path('student/login/', views.loginView, name='login'),
    path('student/logout/', views.logoutView, name='logout'),
    path('student/update/', views.updateView, name='update'),
    path('student/subjects/', views.subjectView, name='subjects'),
    path('student/marks/<int:pk>/', views.enterMarks, name='marks'),
    path('student/select_semester/', views.selectSemester, name='select_semester'),
    #path('routine/', views.routine, name='routine'),
]

student_record/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static


def profile_view(request):
    return HttpResponse("Welcome %s" % request.user)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('student.urls')),
    path('accounts/profile/', profile_view),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

student/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=100, null=True)
    code = models.CharField(max_length=3, null=True)

    def __str__(self):
        return self.name

class AllSubject(models.Model): #Admin can Enter all the available subjects with their credit points and students can choose from it
    name = models.CharField(max_length=50, null=True)
    code = models.CharField(max_length=10, null=True)
    credit_points = models.IntegerField(null=True)

    def __str__(self):
        return self.name

class AllSemester(models.Model): # student can select their Semesters from this table
    SEMESTER = (
        ('First Semester', 'First Semester'),
        ('Second Semester', 'Second Semester'),
        ('Third Semester', 'Third Semester'),
        ('Fourth Semester', 'Fourth Semester'),
        ('Fifth Semester', 'Fifth Semester'),
        ('Sixth Semester', 'Sixth Semester'),
        ('Seventh Semester', 'Seventh Semester'),
        ('Eighth Semester', 'Eighth Semester'),
    )
    semester = models.CharField(max_length=20, null=True, choices=SEMESTER)

    def __str__(self):
        return self.semester


class StudentSubject(models.Model): # A model which has the subjects of the students semesterwise
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    semester = models.ForeignKey(AllSemester, on_delete=models.CASCADE, null=True)
    subjects = models.ManyToManyField(AllSubject)

    def __str__(self):
        return (self.student.first_name + ' ' + self.semester.semester)


# Model which has the marks of all subjects of a student in a semester
class StudentMarks(models.Model):  
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    semester = models.ForeignKey(AllSemester, on_delete=models.CASCADE, null=True)
    subject = models.ForeignKey(AllSubject, on_delete=models.CASCADE, null=True,)
    marks = models.FloatField(null=True)

    def __str__(self):
        return (self.student.first_name)


class Sgpa(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    semester = models.ForeignKey(AllSemester, on_delete=models.CASCADE, null=True)
    sgpa = models.FloatField(null=True)

    def __str__(self):
        return (self.student.first_name + ' ' + self.semester.semester)

class Cgpa(models.Model):
    student = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    cgpa = models.FloatField(default=0)

    def __str__(self):
        return (self.student.first_name)


class StudentProfile(models.Model):

    student = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    birth_date    = models.DateField(null=True)
    reg           = models.CharField(verbose_name='Registration no.',max_length=8,blank=False,unique=True,null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)
    roll = models.CharField(verbose_name='Roll no.',max_length=8,unique=True,blank=False,null=True)
    address       = models.TextField(verbose_name='Address',blank=False,null=True)
    contact       = models.CharField(max_length=13,blank=False,unique=True,null=True)
    photograph    = models.ImageField(upload_to='student/images',null=True, default='student/images/default.png')

    def __str__(self):
        return self.student.username


# USED SIGNALS
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):

    if created:
        StudentProfile.objects.create(student=instance)
        StudentSubject.objects.create(student=instance)
        StudentMarks.objects.create(student=instance)
        Cgpa.objects.create(student=instance)
        Sgpa.objects.create(student=instance)
        print('Profile created')  # Added a print statement for verification

student/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import SelectDateWidget
from django.contrib.auth.models import User
from student.models import StudentProfile, StudentSubject, StudentMarks, AllSubject


class StudentRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]


class StudentProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        fields = '__all__'
        exclude = ['student']


class StudentSubjectForm(forms.ModelForm):
    subjects = forms.ModelMultipleChoiceField(queryset=AllSubject.objects.all(), required=True, widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = StudentSubject
        fields = "__all__"
        exclude = ['student',]

class StudentMarksForm(forms.ModelForm):

    class Meta:
        model = StudentMarks
        fields = '__all__'
        exclude = [
            'student',
            'semester',
        ]

student/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from student.forms import *
from student.models import *
from django.contrib import messages
from django.contrib.auth.models import User
from django.forms import inlineformset_factory
# Create your views here.


# Login View
def loginView(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            student = authenticate(request, username=username, password=password)
            if student is not None:
                login(request, student)
                return redirect('/')
            else:
                messages.info(request, 'Username OR Password is incorrect')
        context = {}
        return render(request, 'student/login_form.html', context=context)


# For Registration
def registerView(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = StudentRegistrationForm()
        if request.method == 'POST':
            form = StudentRegistrationForm(request.POST)
            if form.is_valid():
                form.save()
                student = form.cleaned_data.get('username')
                request.user.studentprofile = request.user
                messages.success(request, 'Accounts was created for '+ student)
                return redirect('student:login')
        context = {
            'form':form
        }
        return render(request, 'student/register_form.html', context=context)


@login_required(login_url='accounts:login')
def logoutView(request):
    if not request.user.is_authenticated:
        return redirect('student:login')
    else:
        logout(request)
        return redirect('/')


# Updates the Student Profile
@login_required(login_url='student:login')
def updateView(request):
    student = request.user.studentprofile
    form = StudentProfileUpdateForm(instance=student)
    if request.method == 'POST':
        form = StudentProfileUpdateForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'form':form,
        'student':student,
    }
    return render(request, 'student/update_form.html', context)


# Function for calculating the CGPA
def cal_cgpa(student):
    allSgpa = Sgpa.objects.filter(student=student)
    semesters = Sgpa.objects.filter(student=student).count()
    total = 0
    for sgpa in allSgpa:
        total += sgpa.sgpa
    cgpa = total/semesters
    return cgpa
 

 # Function for calculating SGPA
def cal_sgpa(student,semester):
    student_subject = get_object_or_404(StudentSubject, student=student, semester=semester)
    all_subjects = AllSubject.objects.filter(studentsubject=student_subject)
    total_credits = 0
    credit_points = 0
    points = 0
    for subject in all_subjects:
        marks = StudentMarks.objects.get(student=student, semester=semester, subject=subject)
        if marks.marks >=90:
            points = 10
        elif marks.marks >=80:
            points = 9
        elif marks.marks >=70:
            points = 8
        elif marks.marks >=60:
            points = 7
        elif marks.marks >=50:
            points = 6
        elif marks.marks >=40:
            points = 5
        elif marks.marks >=30:
            points = 4
        credit_points = credit_points + (points*subject.credit_points)
        total_credits = total_credits + subject.credit_points
    sgpa = credit_points/total_credits
    return sgpa


# Function for storing the subjects of a student each semester
@login_required(login_url='student:login')
def subjectView(request):
    student = request.user
    # semesters = StudentSubject.objects.filter(student=student)
    # subjects = StudentSubject.objects.filter(student=student)
    subject_list = []
    semesters = StudentSubject.objects.filter(student=student)
    for semester in semesters:
        student_subject = StudentSubject.objects.get(student=student,semester=semester.semester)
        subjects = AllSubject.objects.filter(studentsubject=student_subject)
        for subject in subjects:
            subject_list.append(
                {
                    'semester':semester.semester,
                    'name':subject.name,
                    'code':subject.code,
                    'credits':subject.credit_points,
                }
            )

    form = StudentSubjectForm()
    if request.method == 'POST':
        form = StudentSubjectForm(request.POST)
        if form.is_valid():
            subject = form.save(commit=False)
            subject.student = student
            subject.save()
            form.save_m2m()
    context = {
        'form':form,
        'student':student,
        'semesters':semesters,
        'subjects':subjects,
        'subject_list':subject_list,
    }
    return render(request,'student/subjects.html', context)


# Function for entering the marks 
@login_required(login_url='student:login')
def enterMarks(request,pk):
    student = request.user
    semester = AllSemester.objects.get(pk=pk)
    student_subject = get_object_or_404(StudentSubject, student=student, semester=semester)
    # all_subjects = AllSubject.objects.filter(studentsubject=student_subject)
    subject_count = AllSubject.objects.filter(studentsubject=student_subject).count()
    MarksFormSet = inlineformset_factory(User, StudentMarks,fields=('semester','subject','marks'), extra=subject_count)
    # form = StudentMarksForm() 
    formset = MarksFormSet(initial = [{'semester':semester,}])
    if request.method == 'POST':
        # form = StudentMarksForm(request.POST)
        formset = MarksFormSet(request.POST, instance=student)
        if formset.is_valid():
            formset.save(commit=False)
            # for each inline element I want to save the semester field to the current semester
            for form in formset:
                form.semester = semester
                formset.save()
            formset.save()
            sgpa = cal_sgpa(student,semester)
            student_sgpa = Sgpa(student=student, semester=semester, sgpa=sgpa)
            student_sgpa.save()
            cgpa = cal_cgpa(student)
            student_cgpa = Cgpa.objects.get(student=student)
            student_cgpa.cgpa = cgpa
            student_cgpa.save()

            return redirect('/')

    context = {
        'formset':formset,
        'student':student,
        # 'all_subjects':all_subjects,
    }
    return render(request, 'student/marks.html', context)


@login_required(login_url='student:login')
def selectSemester(request):
    student = request.user
    semesters = StudentSubject.objects.filter(student=student).count()
    semester_list = AllSemester.objects.all()[:semesters]
    context = {
        'semester_list':semester_list,
    }
    return render(request, 'student/select_semester.html', context)

@login_required(login_url='student:login')
def index(request):
    student = request.user
    cgpa = Cgpa.objects.get(student=student)
    semester_count = Sgpa.objects.filter(student=student).count() + 1
    present_semester = AllSemester.objects.get(pk=semester_count)
    sgpa_list = Sgpa.objects.filter(student=student)

    context = {
        'student':student,
        'cgpa':cgpa,
        'present_semester':present_semester,
        'sgpa_list':sgpa_list,
    }
    return render(request, 'student/index.html',context)

student/templates/student/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>
    {% block title_block %}
        
    {% endblock title_block %}
    </title>

    <style>
		body{
            background-color: #ebeff5;
            }
	</style>
</head>
  <body>
      {% include 'student/navbar.html' %}
      
      {% block body_block %}
          
      {% endblock body_block %}
          
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

student/templates/student/index.html
{% extends 'student/base.html' %}

{% block title_block %}
    Dashboard
{% endblock title_block %}

{% block body_block %}
    <style>
        .profile-pic{
            max-width: 200px;
            max-height:200px;
            margin: 0 auto;
            border-radius: 50px;
        }
        #semester{
            background-color: #66b7c5;
        }
        #department{
            background-color: #418592;
        }
        #cgpa{
            background-color: rgb(80, 201, 177);
        }
    </style>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="col-md">
                    <div class="card text-center text-white  mb-3" id="department">
                        <div class="card-header">
                            <h4 class="card-title">Department</h4>
                        </div>
                        <div class="card-body">
                            <h3 class="card-title">{{ student.studentprofile.department }}</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="col-md">
                    <div class="card text-center text-white  mb-3" id="semester">
                        <div class="card-header">
                            <h4 class="card-title">Present Semester</h4>
                        </div>
                        <div class="card-body">
                            <h3 class="card-title">{{ present_semester }}</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="col-md">
                    <div class="card text-center text-white  mb-3" id="cgpa">
                        <div class="card-header">
                            <h4 class="card-title">CGPA</h4>
                        </div>
                        <div class="card-body">
                            <h3 class="card-title">{{ cgpa.cgpa }}</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <div class="container">
        <div class="jumbotron">
            <h1>Your Performance</h1>
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Semester</th>
                        <th>SGPA</th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for sgpa in sgpa_list %}
                        <tr>
                            <td>{{ sgpa.semester }}</td>
                            <td>{{ sgpa.sgpa }}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>
    </div>
{% endblock body_block %}

student/templates/student/login_form.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    
	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
    <!-- {% include 'student/navbar.html' %} -->
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                            {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>
							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>
				</div>
				{% for message in messages %}
					<p id="messages">{{ message }}</p>
				{% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'student:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

student/templates/student/marks.html
{%  extends 'student/base.html' %}

{% block title_block %}
    Enter Marks
{% endblock title_block %}

{% block body_block %}

<style>
	.profile-pic{
		max-width: 400px;
		max-height:400px;
		margin: 0 auto;
		border-radius: 50px;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<img class="profile-pic" src="{{request.user.studentprofile.photograph.url}}" >
		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">
            <!-- <h3>All Subjects</h3>
            
            {% for subject in all_subjects %}
                {{ subject }} <br>
            {% endfor %} -->
                
            <h3>Enter your Marks</h3>
            <br>
            <br>
			<form method="POST" action="">
				{% csrf_token %}
				{{formset.as_p}}
		
			<input class="btn btn-primary" type="submit" name="Update Subject">
			</form>
		</div>
	</div>
</div>
{% endblock body_block %}

student/templates/student/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">AcadManageR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'student:index' %}">Dashboard<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="https://admin.nitdgp.ac.in/files/academics/notices/2019/12/31/CLASS_ROUTINE_SECOND_SEM_EVEN_19_20_VXY9UQQ.pdf">Routine</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'student:subjects' %}">Subjects</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'student:select_semester' %}">Enter Marks</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="#" style="font-weight: bold;"><i class="fas fa-user"></i> &nbsp&nbsp Hello, {{ user.first_name }}&nbsp&nbsp&nbsp</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'student:update' %}">Update Profile&nbsp&nbsp&nbsp&nbsp&nbsp</a>
          </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'student:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'student:login' %}">Login</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'student:register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

student/templates/student/register_form.html
<!DOCTYPE html>
<html>
<!-- The UI of the Register Page has been taken from internet -->
  <head>
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
      body,
      html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: #7abecc !important;
      }

      .user_card {
        width: 350px;
        margin-top: auto;
        margin-bottom: auto;
        background: #74cfbf;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

      }

      .form_container {
        margin-top: 20px;
      }

      #form-title {
        color: #fff;
      }

      .login_btn {
        width: 100%;
        background: #33ccff !important;
        color: white !important;
      }

      .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
      }

      .login_container {
        padding: 0 2rem;
      }

      .input-group-text {
        background: #f7ba5b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
      }

      .input_user,
      .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
      }

    </style>

  </head>
<!-- {% include 'student/navbar.html' %} -->
  <body>
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <h3 id="form-title">REGISTER ACCOUNT</h3>
          </div>
          <div class="d-flex justify-content-center form_container">

            <form method="POST" action="">
                {% csrf_token %}
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                {{ form.username }}
              </div>
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                {{ form.first_name }}
              </div>
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                {{ form.last_name }}
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                </div>
                {{ form.email }}
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-key"></i></span>
                </div>
                {{ form.password1 }}
              </div>
              <div class="input-group mb-2">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-key"></i></span>
                </div>
                {{ form.password2 }}
              </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Register Account">
              </div>
            </form>
          </div>

          {{ form.errors }}
          
          <div class="mt-4">
            <div class="d-flex justify-content-center links">
              Already have an account? <a href="{% url 'student:login' %}" class="ml-2">Login</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

      //Query All input fields
      var form_fields = document.getElementsByTagName('input')
      form_fields[1].placeholder = 'Username..';
      form_fields[2].placeholder = 'First name..';
      form_fields[3].placeholder = 'Last name..';
      form_fields[4].placeholder = 'Email..';
      form_fields[5].placeholder = 'Enter password...';
      form_fields[6].placeholder = 'Re-enter Password...';


      for (var field in form_fields) {
        form_fields[field].className += ' form-control'
      }

    </script>
  </body>

</html>

student/templates/student/select_semester.html
{% extends 'student/base.html' %}

{% block title_block %}
    Select Semester
{% endblock title_block %}

{% block body_block %}

<style>
	.profile-pic{
		max-width: 400px;
		max-height:400px;
		margin: 0 auto;
		border-radius: 50px;
	}
</style>

<br>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="card card-body">
                <table class="table table-hover">
                    {% for semester in semester_list %}
                        <tr>
                            <td><h3>Enter Your Marks For</h3></td>
                            <td><a href="{% url 'student:marks' semester.pk %}"><button class="btn btn-info btn-sm">{{ semester.semester }}</button></a></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock body_block %}